// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gexneplerhexvawhsuvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdleG5lcGxlcmhleHZhd2hzdXZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2NzcyMTEsImV4cCI6MjA1NDI1MzIxMX0.YekgjP1wArWheu_3wsWZ5w9jXAQFqFUaI85biTxErqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);